# This file is part of the DUDS project. It is subject to the BSD-style
# license terms in the LICENSE file found in the top-level directory of this
# distribution and at https://github.com/jjackowski/duds/blob/master/LICENSE.
# No part of DUDS, including this file, may be copied, modified, propagated,
# or distributed except according to the terms contained in the LICENSE file.

Import('*')

targets = [ ]
for src in Glob('*.bppi'):
	targets.append(env.BppiArc(src))

# make fonts from DUDS easy to load
#dudsFonts = [
#	'font_Vx7.bppi',
#	'font_Vx8B.bppi',
#]
#for src in dudsFonts:
#	targets.append(env.BppiArc('${DUDSSRC}/' + src))

Return('targets')
